export interface Restaurant {
  id: string;
  name: string;
  cuisine: string;
  rating: number;
  reviews: number;
  deliveryTime: string;
  deliveryFee: number;
  image: string;
  priceRange: string;
  distance: string;
  featured: boolean;
  description: string;
  address: string;
  phone: string;
}

export const restaurants: Restaurant[] = [
  // Featured Restaurants
  {
    id: '1',
    name: 'Bella Italia',
    cuisine: 'Italian',
    rating: 4.8,
    reviews: 234,
    deliveryTime: '25-35 min',
    deliveryFee: 49,
    image: 'https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: true,
    description: 'Authentic Italian cuisine with fresh ingredients',
    address: '123 Main Street, Mumbai',
    phone: '+91 98765 43210'
  },
  {
    id: '2',
    name: 'Spice Garden',
    cuisine: 'Indian',
    rating: 4.6,
    reviews: 187,
    deliveryTime: '30-40 min',
    deliveryFee: 29,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.8 km',
    featured: false,
    description: 'Traditional Indian spices and flavors',
    address: '456 Spice Lane, Delhi',
    phone: '+91 98765 43211'
  },
  {
    id: '3',
    name: 'Tokyo Sushi',
    cuisine: 'Japanese',
    rating: 4.9,
    reviews: 312,
    deliveryTime: '20-30 min',
    deliveryFee: 69,
    image: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.5 km',
    featured: true,
    description: 'Fresh sushi and Japanese delicacies',
    address: '789 Sushi Street, Bangalore',
    phone: '+91 98765 43212'
  },

  // Indian Restaurants
  {
    id: '4',
    name: 'Punjabi Dhaba',
    cuisine: 'Punjabi',
    rating: 4.5,
    reviews: 156,
    deliveryTime: '25-35 min',
    deliveryFee: 39,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '0.9 km',
    featured: false,
    description: 'Authentic Punjabi cuisine with rich flavors',
    address: '12 Dhaba Road, Chandigarh',
    phone: '+91 98765 43213'
  },
  {
    id: '5',
    name: 'South Indian Express',
    cuisine: 'South Indian',
    rating: 4.7,
    reviews: 298,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.6 km',
    featured: true,
    description: 'Crispy dosas, fluffy idlis, and authentic South Indian fare',
    address: '34 Temple Street, Chennai',
    phone: '+91 98765 43214'
  },
  {
    id: '6',
    name: 'Rajasthani Rasoi',
    cuisine: 'Rajasthani',
    rating: 4.4,
    reviews: 89,
    deliveryTime: '35-45 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '2.1 km',
    featured: false,
    description: 'Royal Rajasthani cuisine with traditional recipes',
    address: '56 Palace Road, Jaipur',
    phone: '+91 98765 43215'
  },
  {
    id: '7',
    name: 'Bengali Bawarchi',
    cuisine: 'Bengali',
    rating: 4.6,
    reviews: 134,
    deliveryTime: '30-40 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.3 km',
    featured: false,
    description: 'Sweet and savory Bengali delicacies',
    address: '78 Fish Market, Kolkata',
    phone: '+91 98765 43216'
  },
  {
    id: '8',
    name: 'Gujarati Thali House',
    cuisine: 'Gujarati',
    rating: 4.5,
    reviews: 167,
    deliveryTime: '25-35 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '1.0 km',
    featured: false,
    description: 'Complete Gujarati thali with unlimited servings',
    address: '90 Thali Street, Ahmedabad',
    phone: '+91 98765 43217'
  },
  {
    id: '9',
    name: 'Maharashtrian Misal',
    cuisine: 'Maharashtrian',
    rating: 4.3,
    reviews: 78,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.7 km',
    featured: false,
    description: 'Spicy misal pav and Maharashtrian street food',
    address: '12 Misal Lane, Pune',
    phone: '+91 98765 43218'
  },
  {
    id: '10',
    name: 'Kashmiri Kitchen',
    cuisine: 'Kashmiri',
    rating: 4.8,
    reviews: 92,
    deliveryTime: '40-50 min',
    deliveryFee: 55,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.5 km',
    featured: true,
    description: 'Exotic Kashmiri cuisine with aromatic spices',
    address: '34 Valley View, Srinagar',
    phone: '+91 98765 43219'
  },

  // International Cuisines
  {
    id: '11',
    name: 'Dragon Palace',
    cuisine: 'Chinese',
    rating: 4.4,
    reviews: 203,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.8 km',
    featured: false,
    description: 'Authentic Chinese cuisine with Indo-Chinese fusion',
    address: '56 Dragon Street, Mumbai',
    phone: '+91 98765 43220'
  },
  {
    id: '12',
    name: 'Thai Basil',
    cuisine: 'Thai',
    rating: 4.7,
    reviews: 145,
    deliveryTime: '30-40 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.0 km',
    featured: false,
    description: 'Authentic Thai flavors with fresh herbs',
    address: '78 Thai Lane, Delhi',
    phone: '+91 98765 43221'
  },
  {
    id: '13',
    name: 'Mediterranean Delight',
    cuisine: 'Mediterranean',
    rating: 4.6,
    reviews: 118,
    deliveryTime: '35-45 min',
    deliveryFee: 60,
    image: 'https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.3 km',
    featured: false,
    description: 'Fresh Mediterranean cuisine with olive oil and herbs',
    address: '90 Med Street, Bangalore',
    phone: '+91 98765 43222'
  },
  {
    id: '14',
    name: 'Korean BBQ House',
    cuisine: 'Korean',
    rating: 4.5,
    reviews: 87,
    deliveryTime: '30-40 min',
    deliveryFee: 55,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.9 km',
    featured: false,
    description: 'Korean BBQ and traditional Korean dishes',
    address: '12 Seoul Street, Gurgaon',
    phone: '+91 98765 43223'
  },
  {
    id: '15',
    name: 'Mexican Fiesta',
    cuisine: 'Mexican',
    rating: 4.3,
    reviews: 156,
    deliveryTime: '25-35 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.4 km',
    featured: false,
    description: 'Spicy Mexican food with authentic flavors',
    address: '34 Fiesta Road, Mumbai',
    phone: '+91 98765 43224'
  },

  // Fast Food & Casual Dining
  {
    id: '16',
    name: 'Burger Junction',
    cuisine: 'American',
    rating: 4.2,
    reviews: 234,
    deliveryTime: '15-25 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '0.5 km',
    featured: false,
    description: 'Juicy burgers and crispy fries',
    address: '56 Burger Lane, Delhi',
    phone: '+91 98765 43225'
  },
  {
    id: '17',
    name: 'Pizza Corner',
    cuisine: 'Italian',
    rating: 4.4,
    reviews: 189,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '0.8 km',
    featured: false,
    description: 'Wood-fired pizzas with fresh toppings',
    address: '78 Pizza Street, Bangalore',
    phone: '+91 98765 43226'
  },
  {
    id: '18',
    name: 'Sandwich Hub',
    cuisine: 'Continental',
    rating: 4.1,
    reviews: 98,
    deliveryTime: '15-20 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.4 km',
    featured: false,
    description: 'Fresh sandwiches and wraps',
    address: '90 Sandwich Road, Mumbai',
    phone: '+91 98765 43227'
  },
  {
    id: '19',
    name: 'Momos Point',
    cuisine: 'Tibetan',
    rating: 4.5,
    reviews: 167,
    deliveryTime: '20-30 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.6 km',
    featured: false,
    description: 'Steamed and fried momos with spicy chutney',
    address: '12 Momo Lane, Delhi',
    phone: '+91 98765 43228'
  },
  {
    id: '20',
    name: 'Chaat Bazaar',
    cuisine: 'Street Food',
    rating: 4.3,
    reviews: 245,
    deliveryTime: '15-25 min',
    deliveryFee: 15,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.3 km',
    featured: true,
    description: 'Tangy and spicy Indian street food',
    address: '34 Chaat Street, Mumbai',
    phone: '+91 98765 43229'
  },

  // Healthy & Organic
  {
    id: '21',
    name: 'Green Bowl',
    cuisine: 'Healthy',
    rating: 4.6,
    reviews: 134,
    deliveryTime: '20-30 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.0 km',
    featured: false,
    description: 'Fresh salads, smoothie bowls, and healthy meals',
    address: '56 Health Street, Bangalore',
    phone: '+91 98765 43230'
  },
  {
    id: '22',
    name: 'Organic Kitchen',
    cuisine: 'Organic',
    rating: 4.7,
    reviews: 89,
    deliveryTime: '25-35 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.5 km',
    featured: false,
    description: 'Organic ingredients and farm-to-table meals',
    address: '78 Organic Lane, Delhi',
    phone: '+91 98765 43231'
  },
  {
    id: '23',
    name: 'Juice Junction',
    cuisine: 'Beverages',
    rating: 4.4,
    reviews: 156,
    deliveryTime: '10-15 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.5 km',
    featured: false,
    description: 'Fresh fruit juices and smoothies',
    address: '90 Juice Road, Mumbai',
    phone: '+91 98765 43232'
  },

  // Desserts & Sweets
  {
    id: '24',
    name: 'Sweet Dreams',
    cuisine: 'Desserts',
    rating: 4.8,
    reviews: 198,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: true,
    description: 'Cakes, pastries, and sweet treats',
    address: '12 Sweet Lane, Bangalore',
    phone: '+91 98765 43233'
  },
  {
    id: '25',
    name: 'Mithai Ghar',
    cuisine: 'Indian Sweets',
    rating: 4.5,
    reviews: 167,
    deliveryTime: '25-35 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '0.9 km',
    featured: false,
    description: 'Traditional Indian sweets and mithai',
    address: '34 Mithai Street, Delhi',
    phone: '+91 98765 43234'
  },
  {
    id: '26',
    name: 'Ice Cream Paradise',
    cuisine: 'Ice Cream',
    rating: 4.6,
    reviews: 234,
    deliveryTime: '15-25 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.7 km',
    featured: false,
    description: 'Premium ice creams and frozen desserts',
    address: '56 Ice Cream Road, Mumbai',
    phone: '+91 98765 43235'
  },

  // Regional Indian Cuisines (continued)
  {
    id: '27',
    name: 'Andhra Spice',
    cuisine: 'Andhra',
    rating: 4.7,
    reviews: 123,
    deliveryTime: '30-40 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.6 km',
    featured: false,
    description: 'Fiery Andhra cuisine with authentic spices',
    address: '78 Spice Road, Hyderabad',
    phone: '+91 98765 43236'
  },
  {
    id: '28',
    name: 'Kerala Kitchen',
    cuisine: 'Kerala',
    rating: 4.6,
    reviews: 145,
    deliveryTime: '35-45 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '2.0 km',
    featured: false,
    description: 'Coconut-based Kerala cuisine with seafood',
    address: '90 Backwater Lane, Kochi',
    phone: '+91 98765 43237'
  },
  {
    id: '29',
    name: 'Goan Delights',
    cuisine: 'Goan',
    rating: 4.5,
    reviews: 98,
    deliveryTime: '30-40 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.8 km',
    featured: false,
    description: 'Goan seafood and Portuguese-influenced cuisine',
    address: '12 Beach Road, Goa',
    phone: '+91 98765 43238'
  },
  {
    id: '30',
    name: 'Bihari Bhojan',
    cuisine: 'Bihari',
    rating: 4.3,
    reviews: 76,
    deliveryTime: '25-35 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '1.3 km',
    featured: false,
    description: 'Traditional Bihari cuisine with litti chokha',
    address: '34 Bihar Lane, Patna',
    phone: '+91 98765 43239'
  },

  // More International Options
  {
    id: '31',
    name: 'Lebanese Lounge',
    cuisine: 'Lebanese',
    rating: 4.6,
    reviews: 112,
    deliveryTime: '30-40 min',
    deliveryFee: 55,
    image: 'https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.1 km',
    featured: false,
    description: 'Authentic Lebanese cuisine with fresh ingredients',
    address: '56 Lebanon Street, Mumbai',
    phone: '+91 98765 43240'
  },
  {
    id: '32',
    name: 'Turkish Delight',
    cuisine: 'Turkish',
    rating: 4.4,
    reviews: 89,
    deliveryTime: '35-45 min',
    deliveryFee: 60,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.4 km',
    featured: false,
    description: 'Turkish kebabs and traditional dishes',
    address: '78 Turkish Lane, Delhi',
    phone: '+91 98765 43241'
  },
  {
    id: '33',
    name: 'Greek Garden',
    cuisine: 'Greek',
    rating: 4.5,
    reviews: 134,
    deliveryTime: '30-40 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.9 km',
    featured: false,
    description: 'Fresh Greek cuisine with olive oil and feta',
    address: '90 Greek Street, Bangalore',
    phone: '+91 98765 43242'
  },
  {
    id: '34',
    name: 'Vietnamese Pho',
    cuisine: 'Vietnamese',
    rating: 4.7,
    reviews: 156,
    deliveryTime: '25-35 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.5 km',
    featured: false,
    description: 'Authentic Vietnamese pho and fresh spring rolls',
    address: '12 Pho Lane, Mumbai',
    phone: '+91 98765 43243'
  },

  // Specialty & Fusion
  {
    id: '35',
    name: 'Fusion Factory',
    cuisine: 'Fusion',
    rating: 4.4,
    reviews: 178,
    deliveryTime: '30-40 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.7 km',
    featured: false,
    description: 'Creative fusion dishes blending global flavors',
    address: '34 Fusion Road, Delhi',
    phone: '+91 98765 43244'
  },
  {
    id: '36',
    name: 'BBQ Nation',
    cuisine: 'BBQ',
    rating: 4.6,
    reviews: 234,
    deliveryTime: '35-45 min',
    deliveryFee: 60,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.2 km',
    featured: true,
    description: 'Grilled meats and barbecue specialties',
    address: '56 BBQ Street, Bangalore',
    phone: '+91 98765 43245'
  },
  {
    id: '37',
    name: 'Seafood Shack',
    cuisine: 'Seafood',
    rating: 4.5,
    reviews: 167,
    deliveryTime: '30-40 min',
    deliveryFee: 55,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.8 km',
    featured: false,
    description: 'Fresh seafood and coastal cuisine',
    address: '78 Seafood Lane, Mumbai',
    phone: '+91 98765 43246'
  },
  {
    id: '38',
    name: 'Vegan Vibes',
    cuisine: 'Vegan',
    rating: 4.7,
    reviews: 123,
    deliveryTime: '25-35 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.4 km',
    featured: false,
    description: 'Plant-based cuisine with creative vegan dishes',
    address: '90 Vegan Road, Delhi',
    phone: '+91 98765 43247'
  },

  // Coffee & Bakery
  {
    id: '39',
    name: 'Coffee Culture',
    cuisine: 'Coffee',
    rating: 4.5,
    reviews: 189,
    deliveryTime: '15-20 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '0.6 km',
    featured: false,
    description: 'Artisan coffee and light snacks',
    address: '12 Coffee Street, Bangalore',
    phone: '+91 98765 43248'
  },
  {
    id: '40',
    name: 'French Bakery',
    cuisine: 'Bakery',
    rating: 4.6,
    reviews: 145,
    deliveryTime: '20-30 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.1 km',
    featured: false,
    description: 'Fresh croissants, pastries, and French breads',
    address: '34 Bakery Lane, Mumbai',
    phone: '+91 98765 43249'
  },

  // Additional restaurants to reach 100+
  {
    id: '41',
    name: 'Tandoor Express',
    cuisine: 'North Indian',
    rating: 4.4,
    reviews: 198,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.3 km',
    featured: false,
    description: 'Clay oven cooked North Indian specialties',
    address: '56 Tandoor Road, Delhi',
    phone: '+91 98765 43250'
  },
  {
    id: '42',
    name: 'Dosa Delight',
    cuisine: 'South Indian',
    rating: 4.6,
    reviews: 234,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.8 km',
    featured: false,
    description: 'Crispy dosas with variety of fillings',
    address: '78 Dosa Street, Chennai',
    phone: '+91 98765 43251'
  },
  {
    id: '43',
    name: 'Noodle House',
    cuisine: 'Asian',
    rating: 4.3,
    reviews: 167,
    deliveryTime: '25-35 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: false,
    description: 'Asian noodles and stir-fry dishes',
    address: '90 Noodle Lane, Bangalore',
    phone: '+91 98765 43252'
  },
  {
    id: '44',
    name: 'Paratha Point',
    cuisine: 'North Indian',
    rating: 4.2,
    reviews: 145,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.9 km',
    featured: false,
    description: 'Stuffed parathas with fresh butter',
    address: '12 Paratha Street, Delhi',
    phone: '+91 98765 43253'
  },
  {
    id: '45',
    name: 'Biryani Blues',
    cuisine: 'Hyderabadi',
    rating: 4.8,
    reviews: 312,
    deliveryTime: '35-45 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.1 km',
    featured: true,
    description: 'Authentic Hyderabadi biryani with aromatic spices',
    address: '34 Biryani Road, Hyderabad',
    phone: '+91 98765 43254'
  },
  {
    id: '46',
    name: 'Wrap It Up',
    cuisine: 'Continental',
    rating: 4.1,
    reviews: 89,
    deliveryTime: '15-25 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '0.7 km',
    featured: false,
    description: 'Fresh wraps and rolls with healthy fillings',
    address: '56 Wrap Street, Mumbai',
    phone: '+91 98765 43255'
  },
  {
    id: '47',
    name: 'Pasta Palace',
    cuisine: 'Italian',
    rating: 4.5,
    reviews: 178,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.4 km',
    featured: false,
    description: 'Handmade pasta with authentic Italian sauces',
    address: '78 Pasta Lane, Bangalore',
    phone: '+91 98765 43256'
  },
  {
    id: '48',
    name: 'Taco Bell',
    cuisine: 'Mexican',
    rating: 4.0,
    reviews: 234,
    deliveryTime: '20-30 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.0 km',
    featured: false,
    description: 'Mexican fast food with tacos and burritos',
    address: '90 Taco Road, Delhi',
    phone: '+91 98765 43257'
  },
  {
    id: '49',
    name: 'Ramen Republic',
    cuisine: 'Japanese',
    rating: 4.6,
    reviews: 156,
    deliveryTime: '30-40 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.7 km',
    featured: false,
    description: 'Authentic Japanese ramen with rich broths',
    address: '12 Ramen Street, Mumbai',
    phone: '+91 98765 43258'
  },
  {
    id: '50',
    name: 'Salad Station',
    cuisine: 'Healthy',
    rating: 4.4,
    reviews: 123,
    deliveryTime: '20-30 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.1 km',
    featured: false,
    description: 'Fresh salads with organic ingredients',
    address: '34 Salad Lane, Bangalore',
    phone: '+91 98765 43259'
  },

  // Continue with more restaurants...
  {
    id: '51',
    name: 'Mughlai Mahal',
    cuisine: 'Mughlai',
    rating: 4.7,
    reviews: 189,
    deliveryTime: '35-45 min',
    deliveryFee: 55,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.0 km',
    featured: false,
    description: 'Royal Mughlai cuisine with rich gravies',
    address: '56 Mughal Road, Delhi',
    phone: '+91 98765 43260'
  },
  {
    id: '52',
    name: 'Idli Express',
    cuisine: 'South Indian',
    rating: 4.3,
    reviews: 167,
    deliveryTime: '15-25 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.5 km',
    featured: false,
    description: 'Soft idlis with variety of chutneys',
    address: '78 Idli Street, Chennai',
    phone: '+91 98765 43261'
  },
  {
    id: '53',
    name: 'Steak House',
    cuisine: 'Continental',
    rating: 4.8,
    reviews: 145,
    deliveryTime: '40-50 min',
    deliveryFee: 70,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹₹',
    distance: '2.5 km',
    featured: true,
    description: 'Premium steaks and continental cuisine',
    address: '90 Steak Lane, Mumbai',
    phone: '+91 98765 43262'
  },
  {
    id: '54',
    name: 'Dim Sum Delight',
    cuisine: 'Chinese',
    rating: 4.5,
    reviews: 134,
    deliveryTime: '30-40 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.8 km',
    featured: false,
    description: 'Authentic dim sum and Chinese dumplings',
    address: '12 Dim Sum Road, Bangalore',
    phone: '+91 98765 43263'
  },
  {
    id: '55',
    name: 'Kebab Corner',
    cuisine: 'Mughlai',
    rating: 4.4,
    reviews: 198,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.3 km',
    featured: false,
    description: 'Grilled kebabs and tandoor specialties',
    address: '34 Kebab Street, Delhi',
    phone: '+91 98765 43264'
  },

  // Adding more to reach 100+
  {
    id: '56',
    name: 'Smoothie Bar',
    cuisine: 'Beverages',
    rating: 4.2,
    reviews: 89,
    deliveryTime: '10-15 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.4 km',
    featured: false,
    description: 'Fresh fruit smoothies and protein shakes',
    address: '56 Smoothie Lane, Mumbai',
    phone: '+91 98765 43265'
  },
  {
    id: '57',
    name: 'Waffle World',
    cuisine: 'Desserts',
    rating: 4.6,
    reviews: 156,
    deliveryTime: '20-30 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.0 km',
    featured: false,
    description: 'Belgian waffles with variety of toppings',
    address: '78 Waffle Street, Bangalore',
    phone: '+91 98765 43266'
  },
  {
    id: '58',
    name: 'Curry House',
    cuisine: 'Indian',
    rating: 4.5,
    reviews: 234,
    deliveryTime: '30-40 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.5 km',
    featured: false,
    description: 'Traditional Indian curries with aromatic spices',
    address: '90 Curry Road, Delhi',
    phone: '+91 98765 43267'
  },
  {
    id: '59',
    name: 'Sushi Express',
    cuisine: 'Japanese',
    rating: 4.7,
    reviews: 178,
    deliveryTime: '25-35 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.6 km',
    featured: false,
    description: 'Fresh sushi and Japanese appetizers',
    address: '12 Sushi Lane, Mumbai',
    phone: '+91 98765 43268'
  },
  {
    id: '60',
    name: 'Pancake Paradise',
    cuisine: 'American',
    rating: 4.3,
    reviews: 123,
    deliveryTime: '20-30 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: false,
    description: 'Fluffy pancakes with maple syrup and fruits',
    address: '34 Pancake Street, Bangalore',
    phone: '+91 98765 43269'
  },

  // Continue adding more restaurants to reach 100+
  {
    id: '61',
    name: 'Hyderabadi House',
    cuisine: 'Hyderabadi',
    rating: 4.6,
    reviews: 189,
    deliveryTime: '35-45 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '2.0 km',
    featured: false,
    description: 'Authentic Hyderabadi cuisine and biryani',
    address: '56 Hyderabad Road, Hyderabad',
    phone: '+91 98765 43270'
  },
  {
    id: '62',
    name: 'Pav Bhaji Corner',
    cuisine: 'Street Food',
    rating: 4.4,
    reviews: 267,
    deliveryTime: '15-25 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.6 km',
    featured: false,
    description: 'Mumbai style pav bhaji and street snacks',
    address: '78 Pav Bhaji Lane, Mumbai',
    phone: '+91 98765 43271'
  },
  {
    id: '63',
    name: 'Lassi Shop',
    cuisine: 'Beverages',
    rating: 4.2,
    reviews: 145,
    deliveryTime: '10-15 min',
    deliveryFee: 15,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.3 km',
    featured: false,
    description: 'Traditional lassi and yogurt drinks',
    address: '90 Lassi Street, Delhi',
    phone: '+91 98765 43272'
  },
  {
    id: '64',
    name: 'Hakka Noodles',
    cuisine: 'Indo-Chinese',
    rating: 4.3,
    reviews: 198,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.1 km',
    featured: false,
    description: 'Indo-Chinese fusion with hakka noodles',
    address: '12 Hakka Road, Bangalore',
    phone: '+91 98765 43273'
  },
  {
    id: '65',
    name: 'Kulfi Corner',
    cuisine: 'Desserts',
    rating: 4.5,
    reviews: 134,
    deliveryTime: '15-25 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.8 km',
    featured: false,
    description: 'Traditional Indian kulfi and ice creams',
    address: '34 Kulfi Lane, Delhi',
    phone: '+91 98765 43274'
  },

  // Adding final restaurants to complete 100+
  {
    id: '66',
    name: 'Samosa Junction',
    cuisine: 'Street Food',
    rating: 4.1,
    reviews: 178,
    deliveryTime: '15-20 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.5 km',
    featured: false,
    description: 'Crispy samosas with mint chutney',
    address: '56 Samosa Street, Mumbai',
    phone: '+91 98765 43275'
  },
  {
    id: '67',
    name: 'Masala Dosa',
    cuisine: 'South Indian',
    rating: 4.4,
    reviews: 156,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.7 km',
    featured: false,
    description: 'Crispy masala dosa with coconut chutney',
    address: '78 Dosa Road, Chennai',
    phone: '+91 98765 43276'
  },
  {
    id: '68',
    name: 'Chicken Corner',
    cuisine: 'Non-Vegetarian',
    rating: 4.6,
    reviews: 234,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.3 km',
    featured: false,
    description: 'Spicy chicken preparations and curries',
    address: '90 Chicken Lane, Bangalore',
    phone: '+91 98765 43277'
  },
  {
    id: '69',
    name: 'Vada Pav Express',
    cuisine: 'Street Food',
    rating: 4.2,
    reviews: 189,
    deliveryTime: '10-15 min',
    deliveryFee: 15,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.4 km',
    featured: false,
    description: 'Mumbai\'s famous vada pav and street food',
    address: '12 Vada Pav Street, Mumbai',
    phone: '+91 98765 43278'
  },
  {
    id: '70',
    name: 'Chole Bhature',
    cuisine: 'Punjabi',
    rating: 4.5,
    reviews: 167,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.0 km',
    featured: false,
    description: 'Spicy chole with fluffy bhature',
    address: '34 Chole Street, Delhi',
    phone: '+91 98765 43279'
  },

  // Final batch to complete 100+ restaurants
  {
    id: '71',
    name: 'Fish Fry',
    cuisine: 'Seafood',
    rating: 4.3,
    reviews: 123,
    deliveryTime: '25-35 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.4 km',
    featured: false,
    description: 'Fresh fish fry and coastal specialties',
    address: '56 Fish Market, Kochi',
    phone: '+91 98765 43280'
  },
  {
    id: '72',
    name: 'Rajma Rice',
    cuisine: 'North Indian',
    rating: 4.4,
    reviews: 145,
    deliveryTime: '25-35 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: false,
    description: 'Comfort food with rajma and basmati rice',
    address: '78 Rajma Lane, Delhi',
    phone: '+91 98765 43281'
  },
  {
    id: '73',
    name: 'Uttapam House',
    cuisine: 'South Indian',
    rating: 4.2,
    reviews: 98,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.9 km',
    featured: false,
    description: 'Thick uttapam with vegetable toppings',
    address: '90 Uttapam Road, Chennai',
    phone: '+91 98765 43282'
  },
  {
    id: '74',
    name: 'Mutton Curry',
    cuisine: 'Non-Vegetarian',
    rating: 4.6,
    reviews: 178,
    deliveryTime: '35-45 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.8 km',
    featured: false,
    description: 'Tender mutton curry with aromatic spices',
    address: '12 Mutton Street, Hyderabad',
    phone: '+91 98765 43283'
  },
  {
    id: '75',
    name: 'Paneer Palace',
    cuisine: 'Vegetarian',
    rating: 4.5,
    reviews: 156,
    deliveryTime: '25-35 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.1 km',
    featured: false,
    description: 'Fresh paneer dishes and vegetarian curries',
    address: '34 Paneer Lane, Delhi',
    phone: '+91 98765 43284'
  },

  // Continue with more restaurants...
  {
    id: '76',
    name: 'Egg Curry',
    cuisine: 'Bengali',
    rating: 4.3,
    reviews: 134,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.0 km',
    featured: false,
    description: 'Bengali style egg curry with rice',
    address: '56 Egg Street, Kolkata',
    phone: '+91 98765 43285'
  },
  {
    id: '77',
    name: 'Aloo Paratha',
    cuisine: 'Punjabi',
    rating: 4.2,
    reviews: 189,
    deliveryTime: '15-25 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.8 km',
    featured: false,
    description: 'Stuffed aloo paratha with butter and curd',
    address: '78 Paratha Road, Chandigarh',
    phone: '+91 98765 43286'
  },
  {
    id: '78',
    name: 'Fried Rice',
    cuisine: 'Chinese',
    rating: 4.1,
    reviews: 167,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: false,
    description: 'Wok-tossed fried rice with vegetables',
    address: '90 Rice Lane, Mumbai',
    phone: '+91 98765 43287'
  },
  {
    id: '79',
    name: 'Gulab Jamun',
    cuisine: 'Desserts',
    rating: 4.7,
    reviews: 145,
    deliveryTime: '15-25 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.6 km',
    featured: false,
    description: 'Soft gulab jamun in sugar syrup',
    address: '12 Sweet Lane, Delhi',
    phone: '+91 98765 43288'
  },
  {
    id: '80',
    name: 'Masala Chai',
    cuisine: 'Beverages',
    rating: 4.4,
    reviews: 234,
    deliveryTime: '10-15 min',
    deliveryFee: 15,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.3 km',
    featured: false,
    description: 'Aromatic masala chai with spices',
    address: '34 Chai Street, Mumbai',
    phone: '+91 98765 43289'
  },

  // Final restaurants to complete 100+
  {
    id: '81',
    name: 'Butter Chicken',
    cuisine: 'Punjabi',
    rating: 4.8,
    reviews: 298,
    deliveryTime: '30-40 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.5 km',
    featured: true,
    description: 'Creamy butter chicken with naan',
    address: '56 Butter Lane, Delhi',
    phone: '+91 98765 43290'
  },
  {
    id: '82',
    name: 'Rasam Rice',
    cuisine: 'South Indian',
    rating: 4.3,
    reviews: 123,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.9 km',
    featured: false,
    description: 'Tangy rasam with steamed rice',
    address: '78 Rasam Road, Chennai',
    phone: '+91 98765 43291'
  },
  {
    id: '83',
    name: 'Seekh Kebab',
    cuisine: 'Mughlai',
    rating: 4.5,
    reviews: 167,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.3 km',
    featured: false,
    description: 'Grilled seekh kebabs with mint chutney',
    address: '90 Kebab Street, Lucknow',
    phone: '+91 98765 43292'
  },
  {
    id: '84',
    name: 'Poha Junction',
    cuisine: 'Maharashtrian',
    rating: 4.2,
    reviews: 145,
    deliveryTime: '15-20 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.5 km',
    featured: false,
    description: 'Light and fluffy poha with peanuts',
    address: '12 Poha Lane, Pune',
    phone: '+91 98765 43293'
  },
  {
    id: '85',
    name: 'Dal Makhani',
    cuisine: 'Punjabi',
    rating: 4.6,
    reviews: 189,
    deliveryTime: '30-40 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: false,
    description: 'Rich and creamy dal makhani',
    address: '34 Dal Street, Delhi',
    phone: '+91 98765 43294'
  },

  // Final 15 restaurants to complete 100
  {
    id: '86',
    name: 'Upma Express',
    cuisine: 'South Indian',
    rating: 4.1,
    reviews: 98,
    deliveryTime: '15-25 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.7 km',
    featured: false,
    description: 'Healthy upma with vegetables',
    address: '56 Upma Road, Bangalore',
    phone: '+91 98765 43295'
  },
  {
    id: '87',
    name: 'Chicken Biryani',
    cuisine: 'Hyderabadi',
    rating: 4.7,
    reviews: 234,
    deliveryTime: '35-45 min',
    deliveryFee: 50,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.8 km',
    featured: true,
    description: 'Aromatic chicken biryani with raita',
    address: '78 Biryani Lane, Hyderabad',
    phone: '+91 98765 43296'
  },
  {
    id: '88',
    name: 'Jalebi Corner',
    cuisine: 'Desserts',
    rating: 4.4,
    reviews: 156,
    deliveryTime: '15-25 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.8 km',
    featured: false,
    description: 'Crispy jalebi with sugar syrup',
    address: '90 Jalebi Street, Delhi',
    phone: '+91 98765 43297'
  },
  {
    id: '89',
    name: 'Manchurian',
    cuisine: 'Indo-Chinese',
    rating: 4.3,
    reviews: 178,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.1 km',
    featured: false,
    description: 'Spicy manchurian with fried rice',
    address: '12 Manchurian Road, Mumbai',
    phone: '+91 98765 43298'
  },
  {
    id: '90',
    name: 'Kheer House',
    cuisine: 'Desserts',
    rating: 4.5,
    reviews: 134,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.0 km',
    featured: false,
    description: 'Traditional rice kheer with nuts',
    address: '34 Kheer Lane, Delhi',
    phone: '+91 98765 43299'
  },
  {
    id: '91',
    name: 'Pani Puri',
    cuisine: 'Street Food',
    rating: 4.2,
    reviews: 267,
    deliveryTime: '10-15 min',
    deliveryFee: 15,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.4 km',
    featured: false,
    description: 'Crispy pani puri with spicy water',
    address: '56 Pani Puri Street, Mumbai',
    phone: '+91 98765 43300'
  },
  {
    id: '92',
    name: 'Medu Vada',
    cuisine: 'South Indian',
    rating: 4.3,
    reviews: 145,
    deliveryTime: '15-25 min',
    deliveryFee: 20,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.6 km',
    featured: false,
    description: 'Crispy medu vada with sambar',
    address: '78 Vada Road, Chennai',
    phone: '+91 98765 43301'
  },
  {
    id: '93',
    name: 'Tandoori Roti',
    cuisine: 'North Indian',
    rating: 4.1,
    reviews: 123,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.9 km',
    featured: false,
    description: 'Fresh tandoori roti from clay oven',
    address: '90 Roti Lane, Delhi',
    phone: '+91 98765 43302'
  },
  {
    id: '94',
    name: 'Fish Curry',
    cuisine: 'Coastal',
    rating: 4.6,
    reviews: 167,
    deliveryTime: '30-40 min',
    deliveryFee: 45,
    image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.7 km',
    featured: false,
    description: 'Coconut-based fish curry with rice',
    address: '12 Fish Lane, Goa',
    phone: '+91 98765 43303'
  },
  {
    id: '95',
    name: 'Aloo Gobi',
    cuisine: 'North Indian',
    rating: 4.2,
    reviews: 134,
    deliveryTime: '25-35 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.1 km',
    featured: false,
    description: 'Dry aloo gobi with Indian spices',
    address: '34 Aloo Street, Delhi',
    phone: '+91 98765 43304'
  },
  {
    id: '96',
    name: 'Coconut Rice',
    cuisine: 'South Indian',
    rating: 4.4,
    reviews: 156,
    deliveryTime: '20-30 min',
    deliveryFee: 25,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.8 km',
    featured: false,
    description: 'Fragrant coconut rice with curry leaves',
    address: '56 Coconut Road, Chennai',
    phone: '+91 98765 43305'
  },
  {
    id: '97',
    name: 'Malai Kofta',
    cuisine: 'North Indian',
    rating: 4.5,
    reviews: 189,
    deliveryTime: '30-40 min',
    deliveryFee: 40,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹₹',
    distance: '1.4 km',
    featured: false,
    description: 'Rich malai kofta in creamy gravy',
    address: '78 Kofta Lane, Delhi',
    phone: '+91 98765 43306'
  },
  {
    id: '98',
    name: 'Bhel Puri',
    cuisine: 'Street Food',
    rating: 4.3,
    reviews: 234,
    deliveryTime: '10-15 min',
    deliveryFee: 15,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹',
    distance: '0.3 km',
    featured: false,
    description: 'Tangy bhel puri with chutneys',
    address: '90 Bhel Street, Mumbai',
    phone: '+91 98765 43307'
  },
  {
    id: '99',
    name: 'Rava Dosa',
    cuisine: 'South Indian',
    rating: 4.4,
    reviews: 178,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    image: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.0 km',
    featured: false,
    description: 'Crispy rava dosa with potato filling',
    address: '12 Rava Road, Bangalore',
    phone: '+91 98765 43308'
  },
  {
    id: '100',
    name: 'Kulcha Corner',
    cuisine: 'Punjabi',
    rating: 4.6,
    reviews: 167,
    deliveryTime: '25-35 min',
    deliveryFee: 35,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    priceRange: '₹₹',
    distance: '1.2 km',
    featured: false,
    description: 'Stuffed kulcha with chole and pickle',
    address: '34 Kulcha Street, Amritsar',
    phone: '+91 98765 43309'
  }
];

export const getCuisines = (): string[] => {
  const cuisines = Array.from(new Set(restaurants.map(r => r.cuisine)));
  return ['all', ...cuisines.sort()];
};

export const getFeaturedRestaurants = (): Restaurant[] => {
  return restaurants.filter(r => r.featured);
};

export const getRestaurantById = (id: string): Restaurant | undefined => {
  return restaurants.find(r => r.id === id);
};